type Query {
    oescobarPost(id: Int!): OEscobarPost @resolver(class: "OEscobar\\Blog\\Model\\Resolver\\Post\\GetPost")
    oescobarPosts(pageSize: Int = 20, currentPage: Int = 1, search: String): OEscobarPostSearchResult @resolver(class: "OEscobar\\Blog\\Model\\Resolver\\Post\\GetPosts")
}

type OEscobarPost {
    post_id: Int!
    title: String!
    content: String!
    author: String
    status: Int
    created_at: String
    updated_at: String
    comments(pageSize: Int = 20, currentPage: Int = 1): OEscobarCommentSearchResult @resolver(class: "OEscobar\\Blog\\Model\\Resolver\\Post\\Comments")
}

type OEscobarComment {
    comment_id: Int!
    post_id: Int!
    content: String!
    author: String
    status: Int
    created_at: String
}

type OEscobarPostSearchResult {
    items: [OEscobarPost!]!
    total_count: Int!
}

type OEscobarCommentSearchResult {
    items: [OEscobarComment!]!
    total_count: Int!
}
